## global
seed: 0
device: cuda
mode: train
best_path: None 

## data 
data_dir: data
dataset: NYCBike1  
input_length: 19 # 4+5*3
batch_size: 32
test_batch_size: 32
graph_file: data/NYCBike1/adj_mx.npz # 128 x 128

## model 
d_input: 2                  # means inflow and outflow
d_output: 2                 # means inflow and outflow
d_model: 64
dropout: 0.2
yita: 0.5                   # balance for inflow loss and outflow loss, $yita * inflow + (1 - yita) * outflow$

## train
pretrain_epochs: 200
epochs: 200
lr_init: 0.001
early_stop: True
pretrain_early_stop_patience: 15
retrain_early_stop_patience: 30
grad_norm: True
max_grad_norm: 5
weight_decay1: 0
weight_decay2: 0.000001
weight_decay3: 0

## ARP-settings
pretrain_rate: 0.5          # rate of pretrain data
alpha: 0.8
beta: 0.9
pretrain: True